### ISSUE TITLE
Provide Gradle Plugin to scan project

### ISSUE THREAD

**Issue by lostiniceland** [jQAssistant/jQA-Idea-Hub#19] opened 2021-06-09 08:01 UTC
Currently there is only a custom Gradle plugin to scan a project with JQAssistant. The configuration is much more complex compared to the official maven-plugin.

http://techblog.kontext-e.de/jqassistant-with-gradle/

It would be great if there would be an official Gradle plugin

**Comment by obfischer** [comment] 2021-06-20 18:31
Duplicate of jQAssistant/jQA-Idea-Hub#7.

**Closed by obfischer** 2021-06-20 18:31 UTC
Labels: status:done, status:duplicate
